# Generated by Django 4.2.6 on 2024-10-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('start_dt', models.DateField()),
                ('end_dt', models.DateField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
            ],
        ),
    ]
