# Generated by Django 4.2.6 on 2024-10-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.cost'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='予算')),
                ('peyment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='app.payment')),
            ],
        ),
    ]
