# Generated by Django 4.2.6 on 2024-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.IntegerField(default=2),
        ),
    ]
