# Generated by Django 4.2.6 on 2024-10-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost_genre',
            field=models.CharField(choices=[('food', '食費'), ('traffic', '交通費'), ('entertainment', 'エンタメ'), ('souvenir', 'お土産'), ('other', 'その他')], default='食費', max_length=30, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_payers',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='支払者'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_wallet',
            field=models.CharField(choices=[('shared', '共有の財布'), ('personal', '個人の財布')], default='共有の財布', max_length=10, verbose_name='財布の種類'),
        ),
    ]
