# Generated by Django 4.2.6 on 2024-10-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
