# Generated by Django 4.2.6 on 2024-11-08 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スポット名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('category', models.CharField(choices=[('観光地', '観光地'), ('レストラン', 'レストラン'), ('カフェ', 'カフェ'), ('自然スポット', '自然スポット')], max_length=50, verbose_name='カテゴリー')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='営業時間')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='料金')),
                ('rating', models.FloatField(verbose_name='評価')),
                ('notes', models.TextField(blank=True, verbose_name='補足')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sei', models.CharField(max_length=50)),
                ('sei_kana', models.CharField(max_length=50)),
                ('mei', models.CharField(max_length=50)),
                ('mei_kana', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('relationship_proof', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
