# Generated by Django 4.2.6 on 2024-11-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_schedule_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
