# Generated by Django 4.2.6 on 2024-11-19 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_application_applicant_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '拒否')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='mei_kana',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='フリガナはカタカナで入力してください。', regex='^[ァ-ヶー]+$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='sei_kana',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='フリガナはカタカナで入力してください。', regex='^[ァ-ヶー]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号の形式が正しくありません。', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='spot',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='評価'),
        ),
    ]
