# Generated by Django 4.2.6 on 2024-11-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_application_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_approved',
            new_name='status',
        ),
    ]
